# This file was auto-generated by Fern from our API Definition.

import typing

from .catalog_sandbox_provider_auto_archive_interval_in_minutes import (
    CatalogSandboxProviderAutoArchiveIntervalInMinutes,
)
from .catalog_sandbox_provider_sandbox_timeout_ms import CatalogSandboxProviderSandboxTimeoutMs

CatalogSandboxProvider = typing.Union[
    CatalogSandboxProviderAutoArchiveIntervalInMinutes, CatalogSandboxProviderSandboxTimeoutMs
]
