# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DiscoveredModel(UncheckedBaseModel):
    context_length: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum context window in tokens, when the provider reports one.
    """

    max_output_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum output tokens, when the provider reports one.
    """

    model_id: str = pydantic.Field()
    """
    Upstream, provider-specific identifier sent to the provider API.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
