# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .chat_instruction_source import ChatInstructionSource


class GeneratedSessionInstructions(UncheckedBaseModel):
    current_instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    Instructions currently on the session or named agent, if any.
    """

    instructions: str = pydantic.Field()
    """
    Suggested system instructions. Not applied until the client saves them.
    """

    sources: typing.List[ChatInstructionSource] = pydantic.Field()
    """
    Transcript excerpts the suggestion was inferred from.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
