# This file was auto-generated by Fern from our API Definition.

import typing

from .sandbox_provider_manifest_auto_archive_interval_in_minutes import (
    SandboxProviderManifestAutoArchiveIntervalInMinutes,
)
from .sandbox_provider_manifest_sandbox_timeout_ms import SandboxProviderManifestSandboxTimeoutMs

SandboxProviderManifest = typing.Union[
    SandboxProviderManifestAutoArchiveIntervalInMinutes, SandboxProviderManifestSandboxTimeoutMs
]
