# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .e2b_sandbox_provider_auth import E2BSandboxProviderAuth


class SandboxProviderManifestSandboxTimeoutMs(UncheckedBaseModel):
    auth: E2BSandboxProviderAuth
    exec_timeout_ms: int = pydantic.Field()
    """
    Default sandbox command exec timeout in milliseconds.
    """

    sandbox_timeout_ms: int = pydantic.Field()
    """
    Maximum lifetime of an E2B sandbox in milliseconds.
    """

    type: typing.Literal["e2b"] = pydantic.Field(default="e2b")
    """
    E2B sandbox provider.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
