// This file was auto-generated by Fern from our API Definition.

/** Speaker of the excerpt. */
export const ChatInstructionSourceRole = {
    User: "user",
    Assistant: "assistant",
} as const;
export type ChatInstructionSourceRole = (typeof ChatInstructionSourceRole)[keyof typeof ChatInstructionSourceRole];
