// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ChatInstructionSource {
    /** Short quote from the transcript used as evidence. */
    excerpt: string;
    /** Speaker of the excerpt. */
    role: TrueForge.ChatInstructionSourceRole;
    /** Turn that contributed this excerpt. */
    turnId: string;
}
