// This file was auto-generated by Fern from our API Definition.

/**
 * E2B authentication credentials.
 */
export interface E2BSandboxProviderAuth {
    /** E2B API key. Responses are redacted; on PUT, a real value sets/rotates and a redacted value keeps the stored key. */
    apiKey: string;
}
