// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface GeneratedSessionInstructions {
    /** Instructions currently on the session or named agent, if any. */
    currentInstructions: string | null;
    /** Suggested system instructions. Not applied until the client saves them. */
    instructions: string;
    /** Transcript excerpts the suggestion was inferred from. */
    sources: TrueForge.ChatInstructionSource[];
}
