// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CatalogSandboxProviderAutoArchiveIntervalInMinutes } from "./CatalogSandboxProviderAutoArchiveIntervalInMinutes.js";
import { CatalogSandboxProviderSandboxTimeoutMs } from "./CatalogSandboxProviderSandboxTimeoutMs.js";

export const CatalogSandboxProvider: core.serialization.Schema<
    serializers.CatalogSandboxProvider.Raw,
    TrueForge.CatalogSandboxProvider
> = core.serialization.undiscriminatedUnion([
    CatalogSandboxProviderAutoArchiveIntervalInMinutes,
    CatalogSandboxProviderSandboxTimeoutMs,
]);

export declare namespace CatalogSandboxProvider {
    export type Raw =
        | CatalogSandboxProviderAutoArchiveIntervalInMinutes.Raw
        | CatalogSandboxProviderSandboxTimeoutMs.Raw;
}
