// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CatalogSandboxProviderSandboxTimeoutMs: core.serialization.ObjectSchema<
    serializers.CatalogSandboxProviderSandboxTimeoutMs.Raw,
    TrueForge.CatalogSandboxProviderSandboxTimeoutMs
> = core.serialization.object({
    execTimeoutMs: core.serialization.property("exec_timeout_ms", core.serialization.number()),
    sandboxTimeoutMs: core.serialization.property("sandbox_timeout_ms", core.serialization.number()),
    type: core.serialization.stringLiteral("e2b"),
});

export declare namespace CatalogSandboxProviderSandboxTimeoutMs {
    export interface Raw {
        exec_timeout_ms: number;
        sandbox_timeout_ms: number;
        type: "e2b";
    }
}
