// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChatInstructionSourceRole: core.serialization.Schema<
    serializers.ChatInstructionSourceRole.Raw,
    TrueForge.ChatInstructionSourceRole
> = core.serialization.enum_(["user", "assistant"]);

export declare namespace ChatInstructionSourceRole {
    export type Raw = "user" | "assistant";
}
