// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChatInstructionSourceRole } from "./ChatInstructionSourceRole.js";

export const ChatInstructionSource: core.serialization.ObjectSchema<
    serializers.ChatInstructionSource.Raw,
    TrueForge.ChatInstructionSource
> = core.serialization.object({
    excerpt: core.serialization.string(),
    role: ChatInstructionSourceRole,
    turnId: core.serialization.property("turn_id", core.serialization.string()),
});

export declare namespace ChatInstructionSource {
    export interface Raw {
        excerpt: string;
        role: ChatInstructionSourceRole.Raw;
        turn_id: string;
    }
}
