// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const E2BSandboxProviderAuth: core.serialization.ObjectSchema<
    serializers.E2BSandboxProviderAuth.Raw,
    TrueForge.E2BSandboxProviderAuth
> = core.serialization.object({
    apiKey: core.serialization.property("api_key", core.serialization.string()),
});

export declare namespace E2BSandboxProviderAuth {
    export interface Raw {
        api_key: string;
    }
}
