// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GeneratedSessionInstructions } from "./GeneratedSessionInstructions.js";

export const GenerateSessionInstructionsResponse: core.serialization.ObjectSchema<
    serializers.GenerateSessionInstructionsResponse.Raw,
    TrueForge.GenerateSessionInstructionsResponse
> = core.serialization.object({
    data: GeneratedSessionInstructions,
});

export declare namespace GenerateSessionInstructionsResponse {
    export interface Raw {
        data: GeneratedSessionInstructions.Raw;
    }
}
