// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChatInstructionSource } from "./ChatInstructionSource.js";

export const GeneratedSessionInstructions: core.serialization.ObjectSchema<
    serializers.GeneratedSessionInstructions.Raw,
    TrueForge.GeneratedSessionInstructions
> = core.serialization.object({
    currentInstructions: core.serialization.property("current_instructions", core.serialization.string().nullable()),
    instructions: core.serialization.string(),
    sources: core.serialization.list(ChatInstructionSource),
});

export declare namespace GeneratedSessionInstructions {
    export interface Raw {
        current_instructions?: string | null;
        instructions: string;
        sources: ChatInstructionSource.Raw[];
    }
}
