// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { E2BSandboxProviderAuth } from "./E2BSandboxProviderAuth.js";

export const SandboxProviderManifestSandboxTimeoutMs: core.serialization.ObjectSchema<
    serializers.SandboxProviderManifestSandboxTimeoutMs.Raw,
    TrueForge.SandboxProviderManifestSandboxTimeoutMs
> = core.serialization.object({
    auth: E2BSandboxProviderAuth,
    execTimeoutMs: core.serialization.property("exec_timeout_ms", core.serialization.number()),
    sandboxTimeoutMs: core.serialization.property("sandbox_timeout_ms", core.serialization.number()),
    type: core.serialization.stringLiteral("e2b"),
});

export declare namespace SandboxProviderManifestSandboxTimeoutMs {
    export interface Raw {
        auth: E2BSandboxProviderAuth.Raw;
        exec_timeout_ms: number;
        sandbox_timeout_ms: number;
        type: "e2b";
    }
}
