// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SandboxProviderManifestAutoArchiveIntervalInMinutes } from "./SandboxProviderManifestAutoArchiveIntervalInMinutes.js";
import { SandboxProviderManifestSandboxTimeoutMs } from "./SandboxProviderManifestSandboxTimeoutMs.js";

export const SandboxProviderManifest: core.serialization.Schema<
    serializers.SandboxProviderManifest.Raw,
    TrueForge.SandboxProviderManifest
> = core.serialization.undiscriminatedUnion([
    SandboxProviderManifestAutoArchiveIntervalInMinutes,
    SandboxProviderManifestSandboxTimeoutMs,
]);

export declare namespace SandboxProviderManifest {
    export type Raw =
        | SandboxProviderManifestAutoArchiveIntervalInMinutes.Raw
        | SandboxProviderManifestSandboxTimeoutMs.Raw;
}
